// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
	export interface GlobalComponents {
		PdfPreview: typeof import('./src/components/custom/pdfPreview.vue')['default'];
		RouterLink: typeof import('vue-router')['RouterLink'];
		RouterView: typeof import('vue-router')['RouterView'];
		VanButton: typeof import('vant/es')['Button'];
		VanCell: typeof import('vant/es')['Cell'];
		VanCellGroup: typeof import('vant/es')['CellGroup'];
		VanCheckbox: typeof import('vant/es')['Checkbox'];
		VanField: typeof import('vant/es')['Field'];
		VanForm: typeof import('vant/es')['Form'];
		VanIcon: typeof import('vant/es')['Icon'];
		VanImage: typeof import('vant/es')['Image'];
		VanList: typeof import('vant/es')['List'];
		VanNavBar: typeof import('vant/es')['NavBar'];
		VanNoticeBar: typeof import('vant/es')['NoticeBar'];
		VanPicker: typeof import('vant/es')['Picker'];
		VanPopup: typeof import('vant/es')['Popup'];
		VanTab: typeof import('vant/es')['Tab'];
		VanTabs: typeof import('vant/es')['Tabs'];
	}
}
